### ISSUE TITLE
downloadJira complains about the presence of a directory it creates

### ISSUE THREAD

**Issue by holdenweb** [geekflyer/jira-to-clubhouse-node#2]
I see you've had no time to work on what could be a very useful utility, so I don't expect this to trigger any action. Thanks for putting it out, though. A very useful idea that I'm surprised Clubhouse haven't yet latched on to.

Running `npm start downloadJira` after installation and configuration craters with an exception when trying to create an already-extant `jira-to-clubhouse-node/src/jira/../../data` directory. Deleting the culprit and re-running repeats the error. From the outside it looks like the code should use the equivalent of `mkdir -p`.

```
(backend) fathead:jira-to-clubhouse-node sholden$ rm -rf data
(backend) fathead:jira-to-clubhouse-node sholden$ npm start downloadJira

> jira-to-clubhouse-node@1.0.0 start /Users/sholden/Felix/Projects/jira-to-clubhouse-node
> ts-node src/cli.ts "downloadJira"

27 users downloaded
Unhandled rejection Error: EEXIST: file already exists, mkdir '/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/../../data'
    at Object.fs.mkdirSync (fs.js:885:18)
    at ensureDataDirExists (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/jira-extraction.ts:4:39)
    at Object.<anonymous> (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/jira-extraction.ts:7:3)
    at step (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/jira-extraction.ts:32:23)
    at Object.next (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/jira-extraction.ts:13:53)
    at /Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/jira-extraction.ts:7:71
    at __awaiter (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/jira-extraction.ts:3:12)
    at Object.exports.downloadAllProjects (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/jira/jira-extraction.ts:6:36)
    at /Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:38:13
    at step (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:32:23)
    at Object.next (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:13:53)
    at fulfilled (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:4:58)
From previous event:
    at step (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:6:124)
    at /Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:7:9
From previous event:
    at __awaiter (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:3:12)
    at /Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:70:16
    at Object.<anonymous> (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/run.ts:10:11)
    at step (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/run.ts:32:23)
    at Object.next (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/run.ts:13:53)
    at /Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/run.ts:7:71
From previous event:
    at __awaiter (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/run.ts:3:12)
    at Object.run [as default] (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/run.ts:44:12)
    at Object.<anonymous> (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/src/cli.ts:34:6)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at Object.<anonymous> (/Users/sholden/Felix/Projects/jira-to-clubhouse-node/node_modules/ts-node/src/_bin.ts:182:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(backend) fathead:jira-to-clubhouse-node sholden$ ls -ld data
drwxr-xr-x  3 sholden  staff  96  1 Feb 10:22 data/
````

**Comment by geekflyer** [comment]
fixed with #3
